"""
QuantLab Core Domain Models
============================
All fundamental domain objects for the quant engine.

These are pure Python dataclasses — no dependency on:
  - FastAPI / HTTP
  - SQLAlchemy / databases
  - Any specific data provider

They can be used standalone in notebooks, tests, scripts,
or by the backend API.

Objects:
  MarketBar           — Single OHLCV bar
  Signal              — Trading signal from a strategy
  Order               — Order to be placed
  Fill                — Record of an executed order
  Position            — Current state of a held position
  Trade               — Closed round-trip trade
  Portfolio           — Full portfolio state at a point in time
  BacktestConfig      — Complete configuration for a backtest run
  PerformanceMetrics  — Full set of performance statistics
  BacktestResult      — Complete backtest output
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import date, datetime
from enum import Enum
from typing import Any

import pandas as pd


# =============================================================================
# Enums
# =============================================================================

class Direction(str, Enum):
    """Signal and position direction."""
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


class OrderSide(str, Enum):
    """Buy or sell."""
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    """Order types supported by the execution simulator."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OrderStatus(str, Enum):
    """Lifecycle status of an order."""
    PENDING = "PENDING"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class PositionSizingMethod(str, Enum):
    """Position sizing strategies."""
    FIXED_QUANTITY = "fixed_quantity"
    FIXED_CAPITAL = "fixed_capital"
    PERCENTAGE_ALLOCATION = "percentage_allocation"
    RISK_BASED = "risk_based"
    VOLATILITY_TARGET = "volatility_target"


# =============================================================================
# MarketBar — single OHLCV bar
# =============================================================================

@dataclass(frozen=True)
class MarketBar:
    """
    A single OHLCV market data bar.

    All prices are floats for numpy/pandas compatibility.
    Timestamp must be UTC-aware.

    This is the object that flows through the event-driven backtester.
    """

    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    timeframe: str = "1d"
    adjusted: bool = True
    source: str = "unknown"

    def __post_init__(self) -> None:
        # Validate at construction time (defensive programming)
        if self.high < self.low:
            raise ValueError(
                f"MarketBar: high ({self.high}) < low ({self.low}) "
                f"for {self.symbol} at {self.timestamp}"
            )
        if self.volume < 0:
            raise ValueError(
                f"MarketBar: volume ({self.volume}) < 0 "
                f"for {self.symbol} at {self.timestamp}"
            )

    @property
    def mid_price(self) -> float:
        """Mid-point of high and low."""
        return (self.high + self.low) / 2.0

    @property
    def typical_price(self) -> float:
        """(High + Low + Close) / 3 — used in some technical indicators."""
        return (self.high + self.low + self.close) / 3.0

    def __repr__(self) -> str:
        return (
            f"MarketBar({self.symbol} {self.timestamp.date()} "
            f"O={self.open:.2f} H={self.high:.2f} L={self.low:.2f} "
            f"C={self.close:.2f} V={self.volume:,})"
        )


# =============================================================================
# Signal — generated by a strategy
# =============================================================================

@dataclass(frozen=True)
class Signal:
    """
    A trading signal generated by a strategy.

    A signal is NOT an order. The risk checker and order router
    convert signals into orders.

    Temporal constraint: signals generated on bar T can only be
    converted to orders that execute on bar T+1 or later.

    strength: 0.0 = no conviction, 1.0 = full conviction
    """

    symbol: str
    timestamp: datetime           # Timestamp of the bar that generated this signal
    direction: Direction
    strength: float               # 0.0–1.0
    strategy_id: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(
                f"Signal strength must be 0.0–1.0, got {self.strength}"
            )

    @property
    def is_entry(self) -> bool:
        return self.direction in (Direction.LONG, Direction.SHORT)

    @property
    def is_exit(self) -> bool:
        return self.direction == Direction.FLAT


# =============================================================================
# Order — instruction to buy/sell
# =============================================================================

@dataclass
class Order:
    """
    An instruction to buy or sell a financial instrument.

    Orders are created by the order router from signals.
    They are passed to the execution simulator.

    Temporal constraint: orders can only execute at prices
    available after the signal's bar timestamp.
    """

    symbol: str
    timestamp: datetime           # Time the order was created
    side: OrderSide
    order_type: OrderType
    quantity: float               # Always positive; side determines direction
    limit_price: float | None = None
    status: OrderStatus = OrderStatus.PENDING
    strategy_id: str = ""
    order_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError(
                f"Order quantity must be positive, got {self.quantity}"
            )
        if self.order_type == OrderType.LIMIT and self.limit_price is None:
            raise ValueError("LIMIT orders require a limit_price")

    def cancel(self) -> None:
        self.status = OrderStatus.CANCELLED

    def __repr__(self) -> str:
        return (
            f"Order({self.side.value} {self.quantity:.2f} {self.symbol} "
            f"@ {self.order_type.value} {self.timestamp})"
        )


# =============================================================================
# Fill — record of an executed order
# =============================================================================

@dataclass(frozen=True)
class Fill:
    """
    An immutable record of an executed (filled) order.

    Fills are generated by the execution simulator and processed
    by the portfolio manager to update positions and cash.

    Cost breakdown is explicit so results always show gross vs net PnL.
    """

    fill_id: str
    order_id: str
    symbol: str
    timestamp: datetime           # Time the fill was executed
    side: OrderSide
    quantity: float               # Shares filled (always positive)
    fill_price: float             # Price at which execution occurred
    commission: float             # Brokerage commission paid (positive = cost)
    slippage: float               # Slippage cost (positive = cost)
    spread_cost: float            # Spread/market impact cost (positive = cost)
    strategy_id: str = ""

    @property
    def total_cost(self) -> float:
        return self.commission + self.slippage + self.spread_cost

    @property
    def gross_value(self) -> float:
        """Gross transaction value (before costs)."""
        return self.quantity * self.fill_price

    @property
    def net_value(self) -> float:
        """Net cash change (negative = cash spent, positive = cash received)."""
        sign = -1 if self.side == OrderSide.BUY else 1
        return sign * self.gross_value - self.total_cost

    def __repr__(self) -> str:
        return (
            f"Fill({self.side.value} {self.quantity:.2f} {self.symbol} "
            f"@ {self.fill_price:.4f} | commission={self.commission:.4f} "
            f"slippage={self.slippage:.4f})"
        )


# =============================================================================
# Position — current state of a holding
# =============================================================================

@dataclass
class Position:
    """
    Tracks the current state of a position in a single symbol.

    Updated by the portfolio manager on each fill.
    Provides mark-to-market calculations at any bar.
    """

    symbol: str
    quantity: float = 0.0         # Signed: positive = long, negative = short
    avg_entry_price: float = 0.0
    realized_pnl: float = 0.0

    def apply_fill(self, fill: Fill) -> None:
        """
        Update position state after a fill.
        Handles partial fills, reversals, and full exits correctly.
        """
        fill_qty = fill.quantity if fill.side == OrderSide.BUY else -fill.quantity

        if self.quantity == 0:
            # Opening a new position
            self.quantity = fill_qty
            self.avg_entry_price = fill.fill_price
        elif (self.quantity > 0 and fill_qty > 0) or (self.quantity < 0 and fill_qty < 0):
            # Adding to existing position — update avg entry
            total_qty = self.quantity + fill_qty
            self.avg_entry_price = (
                (self.quantity * self.avg_entry_price + fill_qty * fill.fill_price)
                / total_qty
            )
            self.quantity = total_qty
        else:
            # Reducing or reversing position
            closed_qty = min(abs(fill_qty), abs(self.quantity))
            if self.quantity > 0:
                # Closing long
                self.realized_pnl += closed_qty * (fill.fill_price - self.avg_entry_price)
            else:
                # Closing short
                self.realized_pnl += closed_qty * (self.avg_entry_price - fill.fill_price)

            self.quantity += fill_qty

            if abs(self.quantity) < 1e-9:
                self.quantity = 0.0
                self.avg_entry_price = 0.0
            elif (self.quantity > 0 and fill_qty < 0 and self.quantity + fill_qty < 0) or \
                 (self.quantity < 0 and fill_qty > 0 and self.quantity + fill_qty > 0):
                # Reversal — new position at fill price
                self.avg_entry_price = fill.fill_price

    def unrealized_pnl(self, current_price: float) -> float:
        """Unrealized PnL given current market price."""
        return float(self.quantity) * (float(current_price) - float(self.avg_entry_price))

    def market_value(self, current_price: float) -> float:
        """Current market value of the position."""
        return float(self.quantity) * float(current_price)

    @property
    def is_long(self) -> bool:
        return self.quantity > 0

    @property
    def is_short(self) -> bool:
        return self.quantity < 0

    @property
    def is_flat(self) -> bool:
        return self.quantity == 0

    def __repr__(self) -> str:
        return (
            f"Position({self.symbol}: qty={self.quantity:.2f} "
            f"avg_entry={self.avg_entry_price:.4f} "
            f"realized_pnl={self.realized_pnl:.2f})"
        )


# =============================================================================
# Trade — a closed round-trip
# =============================================================================

@dataclass(frozen=True)
class Trade:
    """
    A completed round-trip trade (entry + exit).

    Trades are created by the portfolio manager when a position is closed.
    They are the basis for trade-level performance analytics.
    """

    trade_id: str
    symbol: str
    side: OrderSide               # Direction of the opening leg
    entry_time: datetime
    exit_time: datetime
    quantity: float
    entry_price: float
    exit_price: float
    gross_pnl: float              # PnL before costs
    costs: float                  # Total transaction costs (both legs)
    strategy_id: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def net_pnl(self) -> float:
        """Net PnL after all transaction costs."""
        return self.gross_pnl - self.costs

    @property
    def return_pct(self) -> float:
        """Return as a percentage of entry value."""
        entry_value = self.quantity * self.entry_price
        if entry_value == 0:
            return 0.0
        return (self.net_pnl / entry_value) * 100.0

    @property
    def holding_bars(self) -> int | None:
        """Number of bars held (None if timestamps unavailable)."""
        return None  # Calculated by metrics engine with actual bar data

    @property
    def duration(self):
        """Duration of the trade."""
        return self.exit_time - self.entry_time

    @property
    def is_winner(self) -> bool:
        return self.net_pnl > 0

    def __repr__(self) -> str:
        return (
            f"Trade({self.symbol} {self.side.value} {self.quantity:.2f} "
            f"| entry={self.entry_price:.4f}@{self.entry_time.date()} "
            f"exit={self.exit_price:.4f}@{self.exit_time.date()} "
            f"| net_pnl={self.net_pnl:.2f})"
        )


# =============================================================================
# Portfolio — portfolio state at a point in time
# =============================================================================

@dataclass
class Portfolio:
    """
    Complete portfolio state at a point in time.

    The PortfolioManager updates this on every bar and after every fill.
    Equity curve is constructed by snapshotting this object.

    Invariant: equity = cash + sum(position market values)
    """

    cash: float
    initial_capital: float
    positions: dict[str, Position] = field(default_factory=dict)
    timestamp: datetime | None = None

    def get_position(self, symbol: str) -> Position:
        """Get or create a position for a symbol."""
        if symbol not in self.positions:
            self.positions[symbol] = Position(symbol=symbol)
        return self.positions[symbol]

    def total_market_value(self, current_prices: dict[str, float]) -> float:
        """Sum of all position market values."""
        return sum(
            pos.market_value(current_prices.get(symbol, pos.avg_entry_price))
            for symbol, pos in self.positions.items()
            if not pos.is_flat
        )

    def equity(self, current_prices: dict[str, float]) -> float:
        """Total portfolio equity = cash + position market values."""
        return self.cash + self.total_market_value(current_prices)

    def total_unrealized_pnl(self, current_prices: dict[str, float]) -> float:
        """Sum of unrealized PnL across all open positions."""
        return sum(
            pos.unrealized_pnl(current_prices.get(symbol, pos.avg_entry_price))
            for symbol, pos in self.positions.items()
            if not pos.is_flat
        )

    def total_realized_pnl(self) -> float:
        """Sum of realized PnL from all positions (includes closed ones)."""
        return sum(pos.realized_pnl for pos in self.positions.values())

    def gross_exposure(self, current_prices: dict[str, float]) -> float:
        """Sum of absolute market values of all positions."""
        return sum(
            abs(pos.market_value(current_prices.get(symbol, pos.avg_entry_price)))
            for symbol, pos in self.positions.items()
            if not pos.is_flat
        )

    def net_exposure(self, current_prices: dict[str, float]) -> float:
        """Net market value (long - short)."""
        return sum(
            pos.market_value(current_prices.get(symbol, pos.avg_entry_price))
            for symbol, pos in self.positions.items()
            if not pos.is_flat
        )

    def leverage(self, current_prices: dict[str, float]) -> float:
        """Gross exposure / equity."""
        eq = self.equity(current_prices)
        if eq == 0:
            return 0.0
        return self.gross_exposure(current_prices) / eq

    def open_positions(self) -> dict[str, Position]:
        """Only positions with non-zero quantity."""
        return {s: p for s, p in self.positions.items() if not p.is_flat}

    def snapshot(self, current_prices: dict[str, float]) -> dict[str, Any]:
        """Create a JSON-serializable snapshot of the portfolio state."""
        eq = self.equity(current_prices)
        return {
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "cash": round(self.cash, 4),
            "equity": round(eq, 4),
            "total_return_pct": round(
                (eq - self.initial_capital) / self.initial_capital * 100, 4
            ) if self.initial_capital > 0 else 0.0,
            "unrealized_pnl": round(self.total_unrealized_pnl(current_prices), 4),
            "realized_pnl": round(self.total_realized_pnl(), 4),
            "gross_exposure": round(self.gross_exposure(current_prices), 4),
            "net_exposure": round(self.net_exposure(current_prices), 4),
            "leverage": round(self.leverage(current_prices), 4),
            "open_positions": {
                symbol: {
                    "quantity": pos.quantity,
                    "avg_entry_price": pos.avg_entry_price,
                    "market_value": pos.market_value(
                        current_prices.get(symbol, pos.avg_entry_price)
                    ),
                    "unrealized_pnl": pos.unrealized_pnl(
                        current_prices.get(symbol, pos.avg_entry_price)
                    ),
                }
                for symbol, pos in self.open_positions().items()
            },
        }


# =============================================================================
# BacktestConfig — complete configuration for a backtest run
# =============================================================================

@dataclass(frozen=True)
class BacktestConfig:
    """
    Complete, immutable configuration for a single backtest run.

    All parameters needed to reproduce the backtest are stored here.
    This object is serialized and stored in the experiments table.

    Note: Changing any field produces a different experiment.
    """

    strategy_id: str
    parameters: dict[str, Any]
    symbols: list[str]
    start_date: date
    end_date: date
    timeframe: str                              # e.g. "1d"
    initial_capital: float
    commission_rate: float                      # e.g. 0.001 = 0.1%
    slippage_bps: float                         # basis points, e.g. 5.0 = 5 bps
    spread_bps: float                           # half-spread each side, e.g. 2.0
    position_sizing: PositionSizingMethod
    sizing_parameter: float = 1.0              # Qty / capital / pct depending on method
    benchmark_symbol: str | None = None
    risk_free_rate: float = 0.0                # Annual, e.g. 0.05 = 5%
    data_source: str = "alpha_vantage"
    adjusted_prices: bool = True
    experiment_id: str | None = None
    notes: str = ""
    seed: int | None = None                    # For reproducibility in Monte Carlo

    def __post_init__(self) -> None:
        if self.initial_capital <= 0:
            raise ValueError(f"initial_capital must be positive, got {self.initial_capital}")
        if self.start_date >= self.end_date:
            raise ValueError(
                f"start_date ({self.start_date}) must be before end_date ({self.end_date})"
            )
        if not self.symbols:
            raise ValueError("symbols list cannot be empty")

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict for storage."""
        return {
            "strategy_id": self.strategy_id,
            "parameters": self.parameters,
            "symbols": self.symbols,
            "start_date": str(self.start_date),
            "end_date": str(self.end_date),
            "timeframe": self.timeframe,
            "initial_capital": self.initial_capital,
            "commission_rate": self.commission_rate,
            "slippage_bps": self.slippage_bps,
            "spread_bps": self.spread_bps,
            "position_sizing": self.position_sizing.value,
            "sizing_parameter": self.sizing_parameter,
            "benchmark_symbol": self.benchmark_symbol,
            "risk_free_rate": self.risk_free_rate,
            "data_source": self.data_source,
            "adjusted_prices": self.adjusted_prices,
            "experiment_id": self.experiment_id,
            "notes": self.notes,
            "seed": self.seed,
        }


# =============================================================================
# PerformanceMetrics — full performance report
# =============================================================================

@dataclass
class PerformanceMetrics:
    """
    Comprehensive performance metrics for a backtest or strategy period.

    All metrics are computed by the metrics engine from actual trade/equity data.
    None of these values are estimated or invented.

    Annualization uses 252 trading days per year.
    """

    # --- Return metrics ---
    total_return: float             # e.g. 0.45 = 45%
    cagr: float                     # Compound Annual Growth Rate
    annualized_return: float        # Same as CAGR for daily data
    annualized_volatility: float    # Annualized std dev of daily returns

    # --- Risk-adjusted returns ---
    sharpe_ratio: float             # (Return - Rf) / Volatility
    sortino_ratio: float            # (Return - Rf) / Downside deviation
    calmar_ratio: float             # CAGR / Max Drawdown

    # --- Drawdown ---
    max_drawdown: float             # e.g. -0.25 = -25%
    max_drawdown_duration: int      # In calendar days
    recovery_time: int | None       # Days to recover from max DD (None if not recovered)

    # --- Trade statistics ---
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: float                 # Winning trades / total trades
    profit_factor: float            # Gross profit / Gross loss (>1 = profitable)
    avg_trade: float                # Average net PnL per trade
    best_trade: float               # Best single net PnL
    worst_trade: float              # Worst single net PnL
    avg_winning_trade: float
    avg_losing_trade: float

    # --- Efficiency ---
    turnover: float                 # Annual portfolio turnover rate

    # --- Time-series data (optional, for charts) ---
    daily_returns: pd.Series | None = None
    monthly_returns: pd.Series | None = None
    yearly_returns: pd.Series | None = None
    rolling_sharpe: pd.Series | None = None

    def to_dict(self) -> dict[str, Any]:
        """JSON-serializable summary (excludes Series fields)."""
        return {
            "total_return": round(self.total_return, 6),
            "cagr": round(self.cagr, 6),
            "annualized_return": round(self.annualized_return, 6),
            "annualized_volatility": round(self.annualized_volatility, 6),
            "sharpe_ratio": round(self.sharpe_ratio, 4),
            "sortino_ratio": round(self.sortino_ratio, 4),
            "calmar_ratio": round(self.calmar_ratio, 4),
            "max_drawdown": round(self.max_drawdown, 6),
            "max_drawdown_duration": self.max_drawdown_duration,
            "recovery_time": self.recovery_time,
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "win_rate": round(self.win_rate, 4),
            "profit_factor": round(self.profit_factor, 4),
            "avg_trade": round(self.avg_trade, 4),
            "best_trade": round(self.best_trade, 4),
            "worst_trade": round(self.worst_trade, 4),
            "avg_winning_trade": round(self.avg_winning_trade, 4),
            "avg_losing_trade": round(self.avg_losing_trade, 4),
            "turnover": round(self.turnover, 4),
        }

    def __repr__(self) -> str:
        return (
            f"PerformanceMetrics("
            f"total_return={self.total_return:.1%} "
            f"cagr={self.cagr:.1%} "
            f"sharpe={self.sharpe_ratio:.2f} "
            f"max_dd={self.max_drawdown:.1%} "
            f"trades={self.total_trades})"
        )


# =============================================================================
# BacktestResult — complete output of a backtest run
# =============================================================================

@dataclass
class BacktestResult:
    """
    Complete, immutable output of a backtest run.

    Contains everything needed to:
    - Display results in the dashboard
    - Compare strategies
    - Store in the database
    - Reproduce the experiment

    Temporal consistency guaranteed: all data was generated by the
    event-driven engine with strict temporal ordering.
    """

    config: BacktestConfig
    metrics: PerformanceMetrics
    equity_curve: pd.Series                    # DatetimeIndex → portfolio equity
    drawdown_series: pd.Series                 # DatetimeIndex → drawdown fraction
    trades: list[Trade]
    portfolio_snapshots: list[dict[str, Any]]  # One per bar
    benchmark_metrics: PerformanceMetrics | None = None
    benchmark_equity_curve: pd.Series | None = None
    warnings: list[str] = field(default_factory=list)
    run_duration_seconds: float = 0.0

    def summary(self) -> str:
        """Human-readable summary of results."""
        m = self.metrics
        lines = [
            f"BacktestResult: {self.config.strategy_id}",
            f"  Period:     {self.config.start_date} → {self.config.end_date}",
            f"  Symbols:    {', '.join(self.config.symbols)}",
            f"  Capital:    ${self.config.initial_capital:,.0f}",
            "  " + "─" * 40,
            f"  Total Return:    {m.total_return:.2%}",
            f"  CAGR:            {m.cagr:.2%}",
            f"  Sharpe Ratio:    {m.sharpe_ratio:.2f}",
            f"  Sortino Ratio:   {m.sortino_ratio:.2f}",
            f"  Calmar Ratio:    {m.calmar_ratio:.2f}",
            f"  Max Drawdown:    {m.max_drawdown:.2%}",
            f"  Ann. Volatility: {m.annualized_volatility:.2%}",
            "  " + "─" * 40,
            f"  Total Trades:    {m.total_trades}",
            f"  Win Rate:        {m.win_rate:.1%}",
            f"  Profit Factor:   {m.profit_factor:.2f}",
            f"  Best Trade:      ${m.best_trade:,.2f}",
            f"  Worst Trade:     ${m.worst_trade:,.2f}",
        ]
        if self.warnings:
            lines.append("  " + "─" * 40)
            lines.append(f"  Warnings: {len(self.warnings)}")
            for w in self.warnings:
                lines.append(f"    ⚠ {w}")
        return "\n".join(lines)
